{% set name = "rocr-runtime" %}
{% set version = "6.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/ROCR-Runtime/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: f72d100a46a2dd9f4c870cef156604777f1bdb1841df039d14bf37b19814b9da

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    # For xxd
    - vim
  host:
    - elfutils
    - rocm-device-libs {{ version }}
    - clangdev 19.*
    - llvmdev  19.*
    - lld      19.*
    - numactl
    - libdrm
    - zlib

test:
  commands:
    - test -f $PREFIX/include/hsa/hsa.h
    - test -f $PREFIX/lib/libhsa-runtime64.so

about:
  home: https://github.com/ROCm/ROCR-Runtime
  license: NCSA
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'ROCm Platform Runtime: ROCr a HPC market enhanced HSA based runtime'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
