{% set name = "rocr-runtime" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/roc-{{ version }}.tar.gz
  sha256: 53c791a46ac8b1c7575e4ae27002cb9e84794a63375e221f7c5447ec928e36e5
  patches:
    - no_override_shared_linker_flags.diff

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - elfutils
    - roct-thunk-interface {{ version }}
  run:
    - {{ pin_compatible("elfutils") }}
    - roct-thunk-interface {{ version }}

test:
  commands:
    - test -f $PREFIX/include/hsa/hsa.h
    - test -f $PREFIX/lib/libhsa-runtime64.so

about:
  home: https://github.com/RadeonOpenCompute/ROCR-Runtime
  license: NCSA
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'ROCm Platform Runtime: ROCr a HPC market enhanced HSA based runtime'

extra:
  recipe-maintainers:
    - isuruf
