{% set name = "rocr-runtime" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/ROCR-Runtime/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: e7ff4d7ac35a2dd8aad1cb40b96511a77a9c23fe4d1607902328e53728e05c28
  patches:
    - fix_xxd_issue.diff

build:
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17   # [linux64]
    - cmake
    - make
    # For xxd
    - vim
  host:
    - elfutils
    - roct-thunk-interface {{ version }}
    - rocm-device-libs {{ version }}
    - clangdev 17.*
    - llvmdev  17.*
    - lld      17.*

test:
  commands:
    - test -f $PREFIX/include/hsa/hsa.h
    - test -f $PREFIX/lib/libhsa-runtime64.so

about:
  home: https://github.com/ROCm/ROCR-Runtime
  license: NCSA
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'ROCm Platform Runtime: ROCr a HPC market enhanced HSA based runtime'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
